
  variable "bh_subnet_id" {}
  variable "bh_nsg_id" {}
  variable "jfrog_subnet_id" {}
  variable "jfrog_nsg_id" {}
  variable "ghe_subnet_id" {}
  variable "ghe_nsg_id" {}
  variable "jenkins_subnet_id" {}
  variable "jenkins_nsg_id" {}
  variable "jira_subnet_id" {}
  variable "jira_nsg_id" {}
  variable "platform_subnet_id" {}
  variable "platform_nsg_id" {}
  variable "sqlserver_subnet_id" {}
  variable "sqlserver_nsg_id" {}
  variable "bitdefender_subnet_id" {}
  variable "bitdefender_nsg_id" {}
  variable "sonarqube_subnet_id" {}
  variable "sonarqube_nsg_id" {}
  variable "selenium_subnet_id" {}
  variable "selenium_nsg_id" {}
  variable "ansible_subnet_id" {}
  variable "ansible_nsg_id" {}
  variable "rediscache_subnet_id" {}
  variable "rediscache_nsg_id" {}
  variable "semmle_subnet_id" {}
  variable "semmle_nsg_id" {}
