    - name: update server packages
      apt:
        upgrade: dist

    - name: install Dependency Packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Download Docker GPG key
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        warn: False

    - name: Setup Docker repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

    - name: update server packages-2
      apt:
        update_cache: yes

    - name: apt-cache plocy for Docker-ce
      shell: apt-cache policy docker-ce

    - name: Install Docker-ce package
      apt:
        name: docker-ce
        state: latest

    - name: Add Jenkins to Docker group
      shell:
        cmd: usermod -aG docker jenkins
        warn: False

