---
  - name: Download nodejs package
    shell:
      cmd: curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
      warn: False

  - name: Setup Nodejs repo
    shell:
      cmd: sh -c "echo deb https://deb.nodesource.com/node_13.x bionic main > /etc/apt/sources.list.d/nodesource.list"
      warn: False

  - name: update packages
    shell:
      cmd: apt-get update
      warn: False

  - name: install nodejs
    apt:
      name: "nodejs"
      state: present
