apiVersion: v1
kind: Service
metadata:
  name: grafana-hs
  labels:
    app: grafana
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: server
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: grafana
spec:
  type: {{ .Values.service.type }}
  selector:
    statefulset.kubernetes.io/pod-name: grafana-0
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
    name: server
  selector:
    app: grafana
